### File for making HTTP calls using Visual Studio Code's REST Client extension
### You can use this file to test out backend url's without needing to run a front end
### Just start the backend server and click on any "Send Request" below to test.
### Requires installation of the REST Client extension by Huachao Mao for VS Code.
### You can specify a requestor ID with or without admin rights to test security

POST http://localhost:4500/message/createMessage HTTP/1.1
content-type: application/json

{
  "requestorId": "5ce9108b0216c5100ca5cfc4",
  "document": {
    "subject": "testmessage4",
    "message": "This is a test message4",
    "receiverId": "5cf0ce5cdff6541c9c127f99",
    "isRead": false,
    "eventType": "Some Other Event Type"
  },
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/message/getMessageById/5d4ba18ada053f03a015e82c HTTP/1.1
content-type: application/json

{
  "project": {"_id": 0, "subject": 1, "message": 1, "senderId": 1},
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/message/getMessagesBySenderId/5ce9108b0216c5100ca5cfc4 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "project": {"_id": 0, "subject": 1, "message": 1, "senderId": 1},
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "options": {"status": "all"}
}

###

POST http://localhost:4500/message/getMessagesByReceiverId/5ce9108b0216c5100ca5cfc4 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "options": {"status": ""}
}

###

POST http://localhost:4500/message/updateMessageById/5d4ba0ccda053f03a015e829 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "document": {
    "message": "New Message Here"
  }
}

###

POST http://localhost:4500/message/deleteMessageById/5d4ba0ccda053f03a015e829 HTTP/1.1
content-type: application/json

{
  "requestorId": "5ce9108b0216c5100ca5cfc4",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###