### File for making HTTP calls using Visual Studio Code's REST Client extension
### You can use this file to test out backend url's without needing to run a front end
### Just start the backend server and click on any "Send Request" below to test.
### Requires installation of the REST Client extension by Huachao Mao for VS Code.
### You can specify a requestor ID with or without admin rights to test security

POST http://localhost:4500/task/createTask HTTP/1.1
content-type: application/json

{
  "requestorId": "5ce9108b0216c5100ca5cfc4",
  "document": {
    "name": "testtask",
    "description": "Test Task",
    "isActive": true,
    "isComplete": false,
    "assignedToId": "5ce9108b0216c5100ca5cfc4"
  },
    "nonadminId": "5cf0ce5cdff6541c9c127f99",
    "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/task/getTaskById/5d4b9b2821cd341cb472afdc HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "project": {"name":1, "isActive":1},
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###
POST http://localhost:4500/task/getTasks HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "project": {},
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###
POST http://localhost:4500/task/updateTaskById/5d4b9b2821cd341cb472afdc HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "document": {
    "isComplete": false
  }
}

###

POST http://localhost:4500/task/deleteTaskById/5d4b9b2821cd341cb472afdc HTTP/1.1
content-type: application/json

{
  "requestorId": "5ce9108b0216c5100ca5cfc4",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###
