### File for making HTTP calls using Visual Studio Code's REST Client extension
### You can use this file to test out backend url's without needing to run a front end
### Just start the backend server and click on any "Send Request" below to test.
### Requires installation of the REST Client extension by Huachao Mao for VS Code.
### You can specify a requestor ID with or without admin rights to test security

POST http://localhost:4500/timesheet/createTimesheet HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "document": {
    "projectId": "5d3ac750a4ad5c0d18196744",
    "dateOfWork": "2019-11-01",
    "utcOffset": -8,
    "totalMinutes": 500,
    "notes": "Some Notes",
    "isTangible": true
  },
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "begDateTime": "2019-10-01:08:30",
  "endDateTime": "2019-10-01:16:30"
}

###

POST http://localhost:4500/timesheet/getTimesheetById/5d4bb380dab4ec139cb940c1 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/timesheet/getTimesheetsByUserId/5ce9108b0216c5100ca5cfc4 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "options": {"begDate": "2019-10-01", "endDate": "2019-12-31"},
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###
POST http://localhost:4500/timesheet/getTimesheetsByDate HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "begDate": "2019-10-01",
  "endDate": "2019-12-30",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/timesheet/updateTimesheetById/5d3eac6149654f16805027d6 HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "document": {
    "isActive": true
  }
}

###

POST http://localhost:4500/timesheet/deleteTimesheetById/5d3eac6149654f16805027d6 HTTP/1.1
content-type: application/json

{
  "requestorId": "5ce9108b0216c5100ca5cfc4",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4"
}

###

POST http://localhost:4500/timesheet/getLeaderboardData HTTP/1.1
content-type: application/json

{
  "requestorId": "5cf0ce5cdff6541c9c127f99",
  "nonadminId": "5cf0ce5cdff6541c9c127f99",
  "adminId": "5ce9108b0216c5100ca5cfc4",
  "startDate": "2019-01-01",
  "endDate": "2019-12-31"
}

